export enum ErrorCode {
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_INVALID_PASSWORD = 'AUTH_INVALID_PASSWORD',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
